export const ERROR_CODES = {
  NO_ACTIVE_DRAFT: 'NO_ACTIVE_DRAFT',
  SUBMISSION_EXISTS: 'SUBMISSION_EXISTS',
  SUBMISSION_LOCKED: 'SUBMISSION_LOCKED',
  NO_SUBMISSION: 'NO_SUBMISSION',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN'
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
